version: '3'
services:
  malmo1:
    image: malmo:latest
    expose:
      - "10000"
  malmo2:
      image: malmo:latest
      expose:
        - "10000"
  agents:
      image: my_exp:latest
      working_dir: /root/malmo-challenge/ai_challenge
      command: bash -c "python main.py malmo1:10000 malmo2:10000 -e rec_value_based_exp -m DQN"
      ports:
        - "6006:6006"
      links:
        - malmo1
        - malmo2